### ISSUE TITLE
Some questions about Amoy testnet

### ISSUE THREAD

**Issue by LilChen1998** [maticnetwork/heimdall#1126] opened 2024-01-11 08:23 UTC
Hello,

Thanks to your meticulous work, I have successfully set up the Amoy test network, which is currently syncing. At the same time, I have a few questions:

First, when will the services for the Mumbai test network be stopped? My project needs this information to determine when to formally migrate to the Amoy test network.

Second, could you provide me with the Explorer and Faucet available for the Amoy test network? They are crucial for my testing work.

Thank you.

**Comment by pratikspatil024** [comment] 2024-01-11 12:52
Duplicate of [bor#1123](https://github.com/maticnetwork/bor/issues/1123).

**Closed by pratikspatil024** 2024-01-11 12:52 UTC
