### ISSUE TITLE
Abnormal Disk Usage Spike During Testnet/Mainnet Snapshot Downloads

### ISSUE THREAD

**Issue by makkanlover** [maticnetwork/heimdall#1072] opened 2023-10-04 01:47 UTC
Hello polygon team.
I want help with some problems I encountered when downloading snapshots.

During the download of the Mumbai testnet snapshot, there was an abnormal increase in disk usage, which resulted in the failure to synchronize with the testnet.

*Specific Symptoms*

My disk configuration is as follows:
・A 30GB EBS volume (let's call it A) under the root path, which is used for synchronization after the download.
・A 1.5TB EBS volume (let's call it B) under the /media/blockdata path, which is used to store the downloaded snapshot.

For both the Testnet and Mainnet environments, the described disk configuration is applied to two instances, C and D. I followed the instructions provided on the website（in the "View script here↓" section） to execute the download command in the /media/blockdata path.
https://wiki.polygon.technology/docs/pos/reference/snapshot-instructions-heimdall-bor/
(The execution was done simultaneously on both instances using a shell script executed by the state manager.)

However, after starting the download, the disk usage of A, the 30GB disk under the root path of environment C, quickly reached close to 100% with an abnormal increase. This increase did not interrupt the download but occupied the disk space of A, resulting in the failure of node synchronization. On the other hand, in environment D, this issue did not occur, and both the download and synchronization processes were completed successfully.

To investigate the environment with the abnormal state and the configured path, I used the 'du' command to check if there were any large files. However, the result showed that there were no large files, so I couldn't determine the cause of this problem. I also consulted the AWS support team, but they believe that it is not caused by technical factors.

*Questions*

From a developer's perspective, does downloading the snapshot using the steps provided in the mentioned website lead to this kind of issue?
What could be the possible cause of this problem, and is there any method to confirm the occurrence process?

**Comment by rebelArtists** [comment] 2023-10-04 19:52
hey @makkanlover thanks for raising this!

we investigated and discovered a bit of docs staleness for the snapdown.sh logic. this is now updated on our public wiki 'view script' section: https://wiki.polygon.technology/docs/pos/reference/snapshot-instructions-heimdall-bor/#client-snapshots

note, our recommended download/extract path is to use the 1-line curl cmd as described in the wiki. it always pulls the latest snapdown.sh logic whereas the logic in 'view scirpt' dropdown is more for reference and may have slight delay in accuracy
`curl -L https://snapshot-download.polygon.technology/snapdown.sh | bash -s -- --network mainnet --client bor --extract-dir chaindata --validate-checksum true`

confident running this new logic should unblock you as we recently resolved a similar inquiry on bor side: https://github.com/maticnetwork/bor/issues/972   ..the root cause is transient checksum errors introduced by turning on caching (even though all parts valid). this updated script automatically conducts retries for any failed snapshot pieces until success occurs. this also explains why one of you machines completed without issue and the other did not

please give the updated logic another try and let us know if you encounter any more issues

**Comment by anshalshukla** [comment] 2023-10-12 06:04
@makkanlover please close the issue if it is fixed

**Closed** 2023-10-12 08:51 UTC
