### ISSUE TITLE
panic: Couldn't find validators at height 14549565 (height 14549598 was originally requested)

### ISSUE THREAD

**Issue by kosmosM** [maticnetwork/heimdall#1015] opened 2023-06-29 09:16 UTC
**Heimdall version** (use `heimdall version` or `git rev-parse --verify HEAD` if installed from source):
0.3.4  (bor version: 0.4.0)

**Environment**:
- **OS** (e.g. from /etc/os-release): linux
- **Install tools**: 
- **Others**:

**What happened**:
panic: Couldn't find validators at height 14549565 (height 14549598 was originally requested)

**What you expected to happen**:
Heimdall syncs normally.

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):
I used [this snapshot](https://snapshot-download.polygon.technology/bor-mainnet-incremental-compiled-files.txt).
I tried the same way in mumbai testnet, but this issue did not happen.

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
panic: Couldn't find validators at height 14549565 (height 14549598 was originally requested)
goroutine 89 [running]:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by Raneet10** [comment] 2023-06-30 05:48
Hey @kosmosM thanks for reporting! We'll try to reproduce this but could you please also share the full error log ?

**Comment by kosmosM** [comment] 2023-07-03 02:55
Thank you for your support. Logs are like this. 
```
2023-07-01T17:50:16.728+09:00	INFO [2023-07-01|08:50:16.728] Genesis file /home/app/config/genesis.json not found, writing genesis file
2023-07-01T17:50:16.728+09:00	module=cmd/heimdalld
2023-07-01T17:50:16.728+09:00	INFO [2023-07-01|08:50:16.728] Heimdall services stopped module=cmd/heimdalld
2023-07-01T17:50:16.814+09:00	INFO [2023-07-01|08:50:16.814] starting ABCI with Tendermint module=main
2023-07-01T17:50:16.814+09:00	INFO [2023-07-01|08:50:16.814] Config file /home/app/config/heimdall-config.toml already exists. Skip writing default heimdall config. module=cmd/heimdalld
2023-07-01T17:50:16.814+09:00	INFO [2023-07-01|08:50:16.814] Found genesis file /home/app/config/genesis.json, skipping writing genesis file
2023-07-01T17:50:16.814+09:00	module=cmd/heimdalld
2023-07-01T17:50:16.845+09:00	DEBUG[2023-07-01|08:50:16.845] Invalid ETH RPC timeout provided, falling back to default value timeout=5s
2023-07-01T17:50:16.845+09:00	DEBUG[2023-07-01|08:50:16.845] Invalid BOR RPC timeout provided, falling back to default value timeout=5s
2023-07-01T17:50:17.964+09:00	panic: Couldn't find validators at height 14574807 (height 14575249 was originally requested)
2023-07-01T17:50:17.964+09:00	goroutine 1 [running]:
2023-07-01T17:50:17.964+09:00	github.com/tendermint/tendermint/state.LoadValidators({0x24d3240, 0xc00053e348}, 0xde6691)
2023-07-01T17:50:17.964+09:00	/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20220923185258-3e7c7f86ce9f/state/store.go:205 +0x194
2023-07-01T17:50:17.964+09:00	github.com/tendermint/tendermint/state.getBeginBlockValidatorInfo(0xc0004f43c0, {0x24d3240, 0xc00053e348})
2023-07-01T17:50:17.964+09:00	/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20220923185258-3e7c7f86ce9f/state/execution.go:413 +0x10d
2023-07-01T17:50:17.964+09:00	github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x24c7cf0, 0xc000509e00}, {0x24d0ba0, 0xc005ea33b0}, 0xc0004f43c0, {0x24d3240, 0xc00053e348}, 0x1)
2023-07-01T17:50:17.964+09:00	/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20220923185258-3e7c7f86ce9f/state/execution.go:294 +0x2df
2023-07-01T17:50:17.964+09:00	github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xa, 0x0}, {0xc005ea0d90, 0x6}}, {0xc005ea0db0, 0xc}, 0xde6691, 0x406694, {{0xc001c18100, ...}, ...}, ...}, ...)
2023-07-01T17:50:17.964+09:00	/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20220923185258-3e7c7f86ce9f/state/execution.go:140 +0x2c9
2023-07-01T17:50:17.964+09:00	github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(_, {{{0xa, 0x0}, {0xc005ea0d90, 0x6}}, {0xc005ea0db0, 0xc}, 0xde6691, 0x406694, {{0xc001c18100, ...}, ...}, ...}, ...)
2023-07-01T17:50:17.964+09:00	/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20220923185258-3e7c7f86ce9f/consensus/replay.go:463 +0x23d
2023-07-01T17:50:17.965+09:00	github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xa, 0x0}, {0xc005ea0d90, 0x6}}, {0xc005ea0db0, 0xc}, 0xde6691, 0x406694, {{0xc001c18100, ...}, ...}, ...}, ...)
2023-07-01T17:50:17.965+09:00	/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20220923185258-3e7c7f86ce9f/consensus/replay.go:387 +0x66e
2023-07-01T17:50:17.965+09:00	github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc006b30e50, {0x24d3a20, 0xc0001f82a0})
2023-07-01T17:50:17.965+09:00	/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20220923185258-3e7c7f86ce9f/consensus/replay.go:269 +0x4e8
2023-07-01T17:50:17.965+09:00	github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xa, 0x0}, {0xc005ea0d90, 0x6}}, {0xc005ea0db0, 0xc}, 0xde6691, 0x406694, ...}, ...)
2023-07-01T17:50:17.965+09:00	/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20220923185258-3e7c7f86ce9f/node/node.go:275 +0x1a5
2023-07-01T17:50:17.965+09:00	github.com/tendermint/tendermint/node.NewNode(0xc000571b80, {0x24c7eb0, 0xc000f66280}, 0xc0011a4300, {0x24b6780, 0xc001ee7e18}, 0xc0000ae0c0?, 0xc0005521e0?, 0xc0011a43c0, {0x24c7cf0, ...}, ...)
2023-07-01T17:50:17.965+09:00	/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20220923185258-3e7c7f86ce9f/node/node.go:582 +0x309
2023-07-01T17:50:17.965+09:00	github.com/maticnetwork/heimdall/cmd/heimdalld/service.startInProcess(0x3f?, {0x24c85b0, 0xc00053a280}, 0xc000562150, 0xc000f580b0, 0xc000f8c000, 0x1, 0x0)
2023-07-01T17:50:17.965+09:00	/go/src/github.com/maticnetwork/heimdall/cmd/heimdalld/service/service.go:433 +0x659
2023-07-01T17:50:17.965+09:00	github.com/maticnetwork/heimdall/cmd/heimdalld/service.heimdallStart.func1(0xc000f56500?, {0xc000f2bad0?, 0x0?, 0xd?})
2023-07-01T17:50:17.965+09:00	/go/src/github.com/maticnetwork/heimdall/cmd/heimdalld/service/service.go:271 +0x16a
2023-07-01T17:50:17.965+09:00	github.com/spf13/cobra.(*Command).execute(0xc000f56500, {0xc000f2b790, 0xd, 0xd})
2023-07-01T17:50:17.965+09:00	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x67c
2023-07-01T17:50:17.965+09:00	github.com/spf13/cobra.(*Command).ExecuteC(0xc000f56000)
2023-07-01T17:50:17.965+09:00	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2ef
2023-07-01T17:50:17.965+09:00	github.com/spf13/cobra.(*Command).Execute(...)
2023-07-01T17:50:17.965+09:00	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
2023-07-01T17:50:17.965+09:00	github.com/tendermint/tendermint/libs/cli.Executor.Execute({0xc000f56000?, 0x1f60fe0?})
2023-07-01T17:50:17.965+09:00	/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20220923185258-3e7c7f86ce9f/libs/cli/setup.go:89 +0x36
2023-07-01T17:50:17.965+09:00	github.com/maticnetwork/heimdall/cmd/heimdalld/service.NewHeimdallService({0x24c6240, 0xc000046040}, {0x0?, 0x0, 0x0})
2023-07-01T17:50:17.965+09:00	/go/src/github.com/maticnetwork/heimdall/cmd/heimdalld/service/service.go:205 +0x6d3
2023-07-01T17:50:17.965+09:00	main.main()
2023-07-01T17:50:17.965+09:00	/go/src/github.com/maticnetwork/heimdall/cmd/heimdalld/main.go:10 +0x2e
```

**Comment by Raneet10** [comment] 2023-07-18 04:08
Hey @kosmosM I was unable to reproduce this. Could you maybe retry syncing your node using the [incremental snapshot mechanism](https://wiki.polygon.technology/docs/pos/reference/snapshot-instructions-heimdall-bor/) ?

**Comment by kosmosM** [comment] 2023-07-22 10:49
Actually my nodes are now running normally by using newer snapshot.
But while I was retrying, I found that though one of my two heimdalls syncs normally the other failed to start because of  the same error.
So, I think this error is not related to snapshot.
I wonder why this error happen and how I can prevent it from occurring again.

**Comment by Raneet10** [comment] 2023-07-22 16:21
> I found that though one of my two heimdalls syncs normally the other failed to start because of the same error.

Was this prior to trying the new snapshot ?

> So, I think this error is not related to snapshot.

My intuition says it's related to malformed state in the snapshot. From what I understand, this panic hits because heimdall is not only able to not fetch validators in the block requested  (`14549598` in this case) but also a previous height at which the validator set had been updated (`14574807` in this case). So I'm still suspecting a corrupted state. Let me know if you have other ideas.

**Comment by kosmosM** [comment] 2023-07-23 14:13
> > I found that though one of my two heimdalls syncs normally the other failed to start because of the same error.
> 
> Was this prior to trying the new snapshot ?

This happend on July 1. After reporting the issue, I tried each day to boot two nodes with the latest snapshot at that time. As a result, two failed to start syncing on June 29 and 30, one of the two failed on July 1, and both of my nodes started successfully on July 2.
Sorry for the confusion, but the error log in the title is for June 29,  and full logs shown in the comment above is for July 1.

I have no idea other than you suggested, but it's odd that the snapshot corrupts so many times.

**Comment by Raneet10** [comment] 2023-07-26 02:59
I see, makes sense. As for the snapshot, we'll try to see what might've gone askew. Let us know if you face any further issues, closing this for now.

**Closed by Raneet10** 2023-07-26 02:59 UTC
